//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NppLogGazer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NppLogGazer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NppLogGazer, Copyright 2016
        ///Created by Tianxing Li 
        ///( litianxing9@gmail.com )
        ///
        ///Press &quot;Show PatternTracer&quot; / &quot;Show QuickSearchPanel&quot; in the menu or toolbar to get started.
        ///
        ///For help, info and updates, visit the site by clicking the &quot;Visit site&quot; button below..
        /// </summary>
        internal static string about_info_text {
            get {
                return ResourceManager.GetString("about_info_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_input {
            get {
                object obj = ResourceManager.GetObject("delete_input", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup at: .
        /// </summary>
        internal static string ex_msg_backup_at {
            get {
                return ResourceManager.GetString("ex_msg_backup_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading default configuration. .
        /// </summary>
        internal static string ex_msg_error_reading_default_config {
            get {
                return ResourceManager.GetString("ex_msg_error_reading_default_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_page_white {
            get {
                object obj = ResourceManager.GetObject("folder_page_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnifier {
            get {
                object obj = ResourceManager.GetObject("magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnifier_bmp {
            get {
                object obj = ResourceManager.GetObject("magnifier_bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap match_case_icon {
            get {
                object obj = ResourceManager.GetObject("match_case_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        internal static string match_case_text {
            get {
                return ResourceManager.GetString("match_case_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap match_word_icon {
            get {
                object obj = ResourceManager.GetObject("match_word_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Word.
        /// </summary>
        internal static string match_word_text {
            get {
                return ResourceManager.GetString("match_word_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pattern_tracer {
            get {
                object obj = ResourceManager.GetObject("pattern_tracer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pattern_tracer_bmp {
            get {
                object obj = ResourceManager.GetObject("pattern_tracer_bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Tracer.
        /// </summary>
        internal static string pattern_tracer_dlg_label {
            get {
                return ResourceManager.GetString("pattern_tracer_dlg_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon pattern_tracer_icon {
            get {
                object obj = ResourceManager.GetObject("pattern_tracer_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern not found..
        /// </summary>
        internal static string pattern_tracer_status_not_found {
            get {
                return ResourceManager.GetString("pattern_tracer_status_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect match only.
        /// </summary>
        internal static string perfect_match_only {
            get {
                return ResourceManager.GetString("perfect_match_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search.
        /// </summary>
        internal static string quick_search_dlg_label {
            get {
                return ResourceManager.GetString("quick_search_dlg_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the keyword..
        /// </summary>
        internal static string quick_search_status_could_not_find {
            get {
                return ResourceManager.GetString("quick_search_status_could_not_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found at line .
        /// </summary>
        internal static string quick_search_status_found_at_line {
            get {
                return ResourceManager.GetString("quick_search_status_found_at_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to search. Ctrl + Click to launch Find dialog..
        /// </summary>
        internal static string quick_search_status_initial_message {
            get {
                return ResourceManager.GetString("quick_search_status_initial_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reg_exp_icon {
            get {
                object obj = ResourceManager.GetObject("reg_exp_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        internal static string regular_expression {
            get {
                return ResourceManager.GetString("regular_expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete duplicated keywords in the list?.
        /// </summary>
        internal static string remove_dup_dlg_message {
            get {
                return ResourceManager.GetString("remove_dup_dlg_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete duplicated keywords.
        /// </summary>
        internal static string remove_dup_dlg_title {
            get {
                return ResourceManager.GetString("remove_dup_dlg_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove_duplicate {
            get {
                object obj = ResourceManager.GetObject("remove_duplicate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap report_disk {
            get {
                object obj = ResourceManager.GetObject("report_disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string result_dlg_label {
            get {
                return ResourceManager.GetString("result_dlg_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string show_about {
            get {
                return ResourceManager.GetString("show_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show PatternTracer.
        /// </summary>
        internal static string show_pattern_tracer {
            get {
                return ResourceManager.GetString("show_pattern_tracer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show QuickSearchPanel.
        /// </summary>
        internal static string show_quick_search_panel {
            get {
                return ResourceManager.GetString("show_quick_search_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://nlg.nex3z.com.
        /// </summary>
        internal static string site_url {
            get {
                return ResourceManager.GetString("site_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap star_bmp {
            get {
                object obj = ResourceManager.GetObject("star_bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_replace {
            get {
                object obj = ResourceManager.GetObject("text_replace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string tooltip_add {
            get {
                return ResourceManager.GetString("tooltip_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Input.
        /// </summary>
        internal static string tooltip_clear_input {
            get {
                return ResourceManager.GetString("tooltip_clear_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string tooltip_delete {
            get {
                return ResourceManager.GetString("tooltip_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Duplicates.
        /// </summary>
        internal static string tooltip_delete_duplicate {
            get {
                return ResourceManager.GetString("tooltip_delete_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Notepad++ Search.
        /// </summary>
        internal static string tooltip_launch_npp_search_dlg {
            get {
                return ResourceManager.GetString("tooltip_launch_npp_search_dlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        internal static string tooltip_match_case {
            get {
                return ResourceManager.GetString("tooltip_match_case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Word.
        /// </summary>
        internal static string tooltip_match_word {
            get {
                return ResourceManager.GetString("tooltip_match_word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string tooltip_move_down {
            get {
                return ResourceManager.GetString("tooltip_move_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string tooltip_move_up {
            get {
                return ResourceManager.GetString("tooltip_move_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        internal static string tooltip_open {
            get {
                return ResourceManager.GetString("tooltip_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        internal static string tooltip_reg_exp {
            get {
                return ResourceManager.GetString("tooltip_reg_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Selected Item.
        /// </summary>
        internal static string tooltip_replace {
            get {
                return ResourceManager.GetString("tooltip_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        internal static string tooltip_save_as {
            get {
                return ResourceManager.GetString("tooltip_save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string tooltip_search {
            get {
                return ResourceManager.GetString("tooltip_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Search.
        /// </summary>
        internal static string tooltip_wrap_search {
            get {
                return ResourceManager.GetString("tooltip_wrap_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wrap_search_icon {
            get {
                object obj = ResourceManager.GetObject("wrap_search_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Search.
        /// </summary>
        internal static string wrap_search_text {
            get {
                return ResourceManager.GetString("wrap_search_text", resourceCulture);
            }
        }
    }
}
